### ISSUE TITLE
Modules 1 and 2 not found

### ISSUE THREAD

**Issue by d8aninja** [microsoft/cloudsqlworkshop#15]
In [this section](https://github.com/microsoft/cloudsqlworkshop?tab=readme-ov-file#-----workshop-modules) it states that "all modules can be found by navigating to the [workshop](https://github.com/microsoft/cloudsqlworkshop/tree/main/cloudsqlworkshop) folder" but that folder only has subdirectories for Modules 3+.  Is it possible to get access to 1+2?

**Comment by rgward** [comment]
thank you for pointing this out. Modules 1 and 2 are only in the slide deck as part of a presentation. I've updated the README to account for this
