### ISSUE TITLE
Requirements for database file placement on SQL VM are imprecise

### ISSUE THREAD

**Issue by dimitri-furman** [microsoft/cloudsqlworkshop#25]
In https://github.com/microsoft/cloudsqlworkshop/blob/main/cloudsqlworkshop/03_Deploy_SQL_AzureVM/readme.md:

> Database files must be stored on a disk other than the OS disk, can use the default drive letter and path from the Azure Portal, and require Premium SSD.

This should explicitly mention that the temporary/ephemeral disk should not be used.

**Comment by rgward** [comment]
Thank you for your feedback. I've added comment to cover this.
