### ISSUE TITLE
Typo in Module 4

### ISSUE THREAD

**Issue by dimitri-furman** [microsoft/cloudsqlworkshop#26]
In https://github.com/microsoft/cloudsqlworkshop/tree/main/cloudsqlworkshop/04_Manage_and_Optimize_SQL_AzureVM, "Microsoft Entra" is misspelled as "Microsoft Entry".

There is another instance of this typo in https://github.com/microsoft/cloudsqlworkshop/tree/main/cloudsqlworkshop/07_Deploy_Manage_Optimize_AzureSQLDB

**Comment by rgward** [comment]
This should be fixed. Can you verify?

**Comment by dimitri-furman** [comment]
Fixed in the first file, but I still see it in the second one.

**Comment by rgward** [comment]
Good catch. Can you verify one more time?

**Comment by dimitri-furman** [comment]
All sorted.
